# Generated by Django 4.0.4 on 2022-06-13 12:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='codi',
            fields=[
                ('codiId', models.IntegerField(primary_key=True, serialize=False)),
                ('coditype', models.CharField(default='', max_length=10)),
                ('codiUrl', models.CharField(default='', max_length=100)),
                ('codiStyle', models.CharField(default='', max_length=10)),
                ('registerDate', models.DateField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Musinsa_Closet',
            fields=[
                ('clothesId', models.IntegerField(primary_key=True, serialize=False)),
                ('closet_title', models.CharField(default='', max_length=200)),
                ('imgUrl', models.CharField(default='', max_length=50)),
                ('mainCategory', models.TextField(choices=[(1, 'Top'), (2, 'Pants'), (3, 'Outer'), (4, 'Onepiece')], default='', max_length=20)),
                ('subCategory', models.TextField(choices=[(0, '기타'), (1, '셔츠/블라우스'), (2, '민소매 티셔츠'), (3, '기타 상의'), (4, '반소매 티셔츠'), (5, '피케/카라 티셔츠'), (6, '긴소매 티셔츠'), (7, '맨투맨/스웨트셔츠'), (8, '후드 티셔츠'), (9, '니트/스웨터'), (10, '숏 팬츠'), (11, '점프 슈트/오버올'), (12, '데님 팬츠'), (13, '코튼 팬츠'), (14, '슈트 팬츠/슬랙스'), (15, '기타 바지'), (16, '트레이닝/조거 팬츠'), (17, '레깅스'), (18, '미디스커트'), (19, '롱스커트'), (20, '미니스커트'), (21, '롱스커트'), (22, '플리스/뽀글이'), (23, '기타 아우터'), (24, '베스트'), (25, '슈트/블레이저 재킷'), (26, '카디건'), (27, '숏패딩/숏헤비 아우터'), (28, '나일론/코치 재킷'), (29, '환절기 코트'), (30, '롱패딩/롱헤비 아우터'), (31, '트러커 재킷'), (32, '겨울 더블 코트'), (33, '겨울 기타 코트'), (34, '겨울 싱글 코트'), (35, '무스탕/퍼'), (36, '트레이닝 재킷'), (37, '사파리/헌팅 재킷'), (38, '패딩 베스트'), (39, '스타디움 재킷'), (40, '아노락 재킷'), (41, '레더/라이더스 재킷'), (42, '원피스')], default='0', max_length=20)),
                ('closet_style', models.CharField(default='', max_length=100)),
                ('closet_color', models.CharField(default='', max_length=100)),
                ('barndName', models.CharField(default='', max_length=50)),
                ('spring', models.BooleanField(default=True)),
                ('summer', models.BooleanField(default=True)),
                ('autumn', models.BooleanField(default=True)),
                ('winter', models.BooleanField(default=True)),
                ('fit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('elasticity', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('transparency', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('thickness', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texture', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price', models.IntegerField(default=1, null=True)),
                ('ragisterDate', models.DateTimeField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='preferences',
            fields=[
                ('preferences_id1', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default='')),
                ('ratingDate', models.DateField(verbose_name=datetime.datetime.now)),
                ('codiId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.codi')),
            ],
        ),
        migrations.CreateModel(
            name='codi_clothes',
            fields=[
                ('cId', models.IntegerField(primary_key=True, serialize=False)),
                ('regDate', models.DateField(verbose_name=datetime.datetime.now)),
                ('clothesId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.musinsa_closet')),
                ('codi_Id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.codi')),
            ],
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('closet_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('closet_title', models.CharField(max_length=200)),
                ('closet_url', models.CharField(max_length=300)),
                ('closet_create_date', models.DateTimeField(auto_now=True)),
                ('closet_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('closet_main_category', models.CharField(default='', max_length=20)),
                ('closet_sub_category', models.TextField(choices=[(0, '기타'), (1, '셔츠/블라우스'), (2, '민소매 티셔츠'), (3, '기타 상의'), (4, '반소매 티셔츠'), (5, '피케/카라 티셔츠'), (6, '긴소매 티셔츠'), (7, '맨투맨/스웨트셔츠'), (8, '후드 티셔츠'), (9, '니트/스웨터'), (10, '숏 팬츠'), (11, '점프 슈트/오버올'), (12, '데님 팬츠'), (13, '코튼 팬츠'), (14, '슈트 팬츠/슬랙스'), (15, '기타 바지'), (16, '트레이닝/조거 팬츠'), (17, '레깅스'), (18, '미디스커트'), (19, '롱스커트'), (20, '미니스커트'), (21, '롱스커트'), (22, '플리스/뽀글이'), (23, '기타 아우터'), (24, '베스트'), (25, '슈트/블레이저 재킷'), (26, '카디건'), (27, '숏패딩/숏헤비 아우터'), (28, '나일론/코치 재킷'), (29, '환절기 코트'), (30, '롱패딩/롱헤비 아우터'), (31, '트러커 재킷'), (32, '겨울 더블 코트'), (33, '겨울 기타 코트'), (34, '겨울 싱글 코트'), (35, '무스탕/퍼'), (36, '트레이닝 재킷'), (37, '사파리/헌팅 재킷'), (38, '패딩 베스트'), (39, '스타디움 재킷'), (40, '아노락 재킷'), (41, '레더/라이더스 재킷'), (42, '원피스')], default='', max_length=20)),
                ('closet_spring', models.BooleanField(default=True)),
                ('closet_summer', models.BooleanField(default=True)),
                ('closet_fall', models.BooleanField(default=True)),
                ('closet_winter', models.BooleanField(default=True)),
                ('closet_color', models.CharField(default='', max_length=100)),
                ('closet_style', models.CharField(default='', max_length=100)),
                ('closet_fit', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
