# Generated by Django 4.0.4 on 2022-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_closet_closet_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='closet_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
